### ISSUE TITLE
Ryan Metz - Draft Brand Statement

### ISSUE THREAD

**Issue by RyanMetz** [ga-students/chicago-outcomes-homework#2]
I’m a technically minded people person with a drive to optimize. My skills in statistical analysis and creative problem solving were honed as a neuroscientist at the University of Chicago and I bring that perspective to data science. I’ve been a leader and a teacher all my life and I’m always looking for a new challenge. I thrive under pressure - when the cards are down, you can count on me.

**Comment by taylorgolden** [comment]
Notes from our conversation: 

I’m a technically minded people person with a drive to optimize, from my route to work to how I do the dishes....

From an early age, I wanted to be a neuroscientist b/c I wanted to learn more about how a computer could do what a brain could do (Doon), I was fascinated and dove headfirst. As I continued to get more involved in the field what I loved the most was X >>> leads you to data science. 

 I’ve been a leader and a teacher all my life and I’m always looking for a new challenge. I thrive under pressure - when the cards are down, you can count on me. >> decide on one of these and get more specific, show the RYAN

**Comment by RyanMetz** [comment]
I’m a technically minded people person with a drive to optimize - from my route to work to how I do the dishes to the perfect regression parameters, I've got to get it just right. I read Dune when I was 14 and decided to become a neuroscientist to develop a way for humans to communicate brain-to-brain. That didn't quite work out but I did become a neuroscientist, most recently working at the University of Chicago. My favorite part of neuroscience was always the math behind brain functions; when I saw what was happening with machine learning I knew I had to join in the fun. I hope your company moves at a fast pace: I thrive under pressure. When I was a backpacking guide in the Rockies I once literally had to fight off a black bear - if the chips are down, you can count on me.
